import type {
  ClientStatus,
  InteractionType,
  Stage,
} from "@/lib/config/stages";

/* ------------------------------------------------------------------ *
 * Core records
 * ------------------------------------------------------------------ */

export interface Contact {
  id: string;
  clientId: string;
  name: string;
  title: string;
  phone: string;
  whatsapp: string;
  email: string;
  isPrimary: boolean;
  notes: string;
  /** How they prefer to be reached. */
  preferredChannel: "whatsapp" | "call" | "email" | "walk_in" | "";
}

export interface Client {
  id: string;
  name: string;
  nameAr: string;
  company: string;
  city: string;
  industry: string;
  website: string;
  sizeGuess: "small" | "mid" | "large" | "";

  stage: Stage;
  status: ClientStatus;

  /** Who owns the relationship. */
  ownerId: string;
  /** Who first brought them in — often, but not always, the owner. */
  broughtById: string;
  /** Anyone else who has also dealt with them. */
  collaboratorIds: string[];

  source: string;
  referredBy: string;

  /** Money. Empty until there are real numbers — by design. */
  dealValueSar: number | null;
  costSar: number | null;

  whatHappened: string;
  whatWeOffered: string;
  objection: string;
  notes: string;
  /** Shown to every member before they go anywhere near this client. */
  teamWarning: string;

  nextAction: string;
  nextActionAt: string | null;

  /** Set when status is `on_hold` or `lost_retryable`. */
  revisitAfter: string | null;

  /** Set when status is `dead`. The reason is mandatory. */
  closedReason: string;
  closedAt: string | null;
  closedById: string;

  firstContactAt: string | null;
  lastContactAt: string | null;

  createdById: string;
  createdAt: string;
  updatedAt: string;
}

export interface Interaction {
  id: string;
  clientId: string;
  memberId: string;
  type: InteractionType;
  happenedAt: string;
  durationMin: number | null;
  summary: string;
  outcome: string;
  stageBefore: Stage | null;
  stageAfter: Stage | null;
}

export type TaskStatus = "open" | "done" | "dropped";
export type Priority = "low" | "normal" | "high";

export interface Task {
  id: string;
  title: string;
  clientId: string | null;
  assigneeId: string;
  dueAt: string | null;
  status: TaskStatus;
  priority: Priority;
  completedAt: string | null;
  createdAt: string;
}

export type AttendanceStatus =
  | "present"
  | "late"
  | "left_early"
  | "absent"
  | "off"
  | "approved_off";

export interface Attendance {
  id: string;
  memberId: string;
  /** yyyy-MM-dd, Riyadh local. */
  date: string;
  checkInAt: string | null;
  checkOutAt: string | null;
  plannedStart: string;
  plannedEnd: string;
  status: AttendanceStatus;
  /** Why they were late, left early, or were absent. */
  reason: string;
  minutesWorked: number;
}

export type DayDecision = "field" | "meeting" | "on" | "off" | "holiday";

export interface ScheduleDay {
  id: string;
  date: string;
  /** null means the decision applies to the whole team. */
  memberId: string | null;
  dayType: DayDecision;
  decidedById: string;
  note: string;
}

/**
 * A note to yourself with a date on it.
 *
 * Warned about as the date approaches, shouted about on the day. Personal by
 * default; setting `sharedWith` puts it in front of the others too.
 */
export interface Reminder {
  id: string;
  memberId: string;
  title: string;
  note: string;
  /** yyyy-MM-dd — reminders are day-precision, not time-precision. */
  dueDate: string;
  /** Days before the date to start warning. */
  warnDaysBefore: number;
  clientId: string | null;
  done: boolean;
  completedAt: string | null;
  /** Set when the member dismisses it for today. */
  snoozedUntil: string | null;
  /** Empty means private to the member who wrote it. */
  sharedWith: string[];
  /** Generated by the system rather than typed — e.g. a stale-client nudge. */
  auto: boolean;
  createdAt: string;
}

export type ReminderUrgency = "overdue" | "today" | "soon" | "later";

/** A message in the team chat. */
export interface Message {
  id: string;
  fromId: string;
  /** null = the group thread with all three. */
  toId: string | null;
  body: string;
  sentAt: string;
  /** Member ids who have opened the thread since this arrived. */
  readBy: string[];
  /** Optional pointer to the client being discussed. */
  clientId: string | null;
}

export interface ThreadSummary {
  /** Other member's id, or null for the group thread. */
  withId: string | null;
  lastMessage: Message | null;
  unread: number;
}

/** Per-member settings that the member can change themselves. */
export interface MemberProfile {
  memberId: string;
  /** Data URL of the member's photo, or "" for initials. */
  photo: string;
  plannedStart: string;
  plannedEnd: string;
  phone: string;
  updatedAt: string;
}

export interface AuditEntry {
  id: string;
  actorId: string;
  entity: "client" | "task" | "attendance" | "schedule";
  entityId: string;
  action: string;
  before: string;
  after: string;
  at: string;
}

/* ------------------------------------------------------------------ *
 * Composed views the UI actually consumes
 * ------------------------------------------------------------------ */

export interface ClientRow extends Client {
  primaryContact: Contact | null;
  lastInteraction: Interaction | null;
  daysSinceContact: number | null;
  interactionCount: number;
  isStale: boolean;
}

export interface ClientDetail extends ClientRow {
  contacts: Contact[];
  interactions: Interaction[];
  tasks: Task[];
  history: AuditEntry[];
}

/* ------------------------------------------------------------------ *
 * Duplicate / collision detection
 * ------------------------------------------------------------------ */

export type MatchReason = "name" | "company" | "phone";

export interface DuplicateMatch {
  client: ClientRow;
  /** 0–1. Above 0.72 we surface it. */
  score: number;
  reason: MatchReason;
  /** How loudly to warn — comes from the matched client's status. */
  level: "info" | "warn" | "block";
}

/* ------------------------------------------------------------------ *
 * Stats, ranges and scoring
 * ------------------------------------------------------------------ */

export type RangeKey = "week" | "month" | "quarter";

export interface DateRange {
  from: string;
  to: string;
  key: RangeKey;
  label: string;
}

export interface EfficiencyBreakdown {
  attendance: number;
  activity: number;
  pipeline: number;
  tasks: number;
}

export interface EfficiencyScore {
  total: number;
  breakdown: EfficiencyBreakdown;
  detail: {
    minutesWorked: number;
    minutesPlanned: number;
    fieldInteractions: number;
    fieldTarget: number;
    stageAdvances: number;
    proposalsSent: number;
    tasksDone: number;
    tasksDueInRange: number;
    tasksLate: number;
  };
}

export interface MemberStats {
  memberId: string;
  range: DateRange;
  clientsTouched: number;
  newClients: number;
  interactions: number;
  visits: number;
  meetings: number;
  calls: number;
  proposalsSent: number;
  stageAdvances: number;
  won: number;
  lost: number;
  dead: number;
  tasksDone: number;
  tasksOpen: number;
  tasksOverdue: number;
  minutesWorked: number;
  minutesPlanned: number;
  daysPresent: number;
  daysLate: number;
  daysAbsent: number;
  efficiency: EfficiencyScore;
  /** One bar per day in the range, for the activity strip. */
  activityByDay: { date: string; count: number }[];
}

/* ------------------------------------------------------------------ *
 * Write payloads
 * ------------------------------------------------------------------ */

export interface NewClientInput {
  name: string;
  nameAr?: string;
  company?: string;
  city?: string;
  industry?: string;
  website?: string;
  stage: Stage;
  status: ClientStatus;
  ownerId: string;
  broughtById: string;
  source?: string;
  referredBy?: string;
  dealValueSar?: number | null;
  whatHappened?: string;
  whatWeOffered?: string;
  objection?: string;
  teamWarning?: string;
  nextAction?: string;
  nextActionAt?: string | null;
  closedReason?: string;
  revisitAfter?: string | null;
  contact?: {
    name: string;
    title?: string;
    phone?: string;
    whatsapp?: string;
    email?: string;
  };
}

export interface NewInteractionInput {
  clientId: string;
  memberId: string;
  type: InteractionType;
  happenedAt?: string;
  durationMin?: number | null;
  summary: string;
  outcome?: string;
  /** When set and different from the current stage, the client advances. */
  newStage?: Stage;
}

export interface ClientFilter {
  ownerId?: string;
  stage?: Stage;
  status?: ClientStatus;
  city?: string;
  search?: string;
  staleOnly?: boolean;
  deadOnly?: boolean;
}

/* ------------------------------------------------------------------ *
 * Bulk import
 * ------------------------------------------------------------------ */

/**
 * One row parsed out of a pasted message, before anyone has confirmed it.
 *
 * The parser guesses; the member corrects. Nothing is written until the
 * preview table is approved, which is why every field here is editable and
 * why `warnings` exists.
 */
export interface ParsedClientRow {
  id: string;
  name: string;
  whatHappened: string;
  city: string;
  contactName: string;
  contactPhone: string;
  stage: Stage;
  status: ClientStatus;
  closedReason: string;
  dealValueSar: number | null;
  /** Set when this looks like a company somebody already has. */
  duplicateOf: { clientId: string; ownerId: string; status: ClientStatus } | null;
  /** Unticked rows are skipped on save. */
  include: boolean;
  /** The original line, kept so the member can see what it came from. */
  raw: string;
}

export interface ParsedActivityRow {
  id: string;
  clientId: string;
  /** What the parser read as the client name, when it could not match one. */
  clientGuess: string;
  type: InteractionType;
  summary: string;
  /** yyyy-MM-dd */
  date: string;
  include: boolean;
  raw: string;
}

export interface SessionUser {
  id: string;
  slot: 1 | 2 | 3;
  name: string;
}
